export const PNGs = {
  LOGO: require('./logo.png'),
  SPLASH_SCREEN: require('./splash_screen.png'),
  LEFT_ARROW: require('./leftArrow.png'),
  CROSS: require('./cross.png'),
  PLAY_ICON: require('./play-button.png'),
  BatBallIcon: require('./batBallIcon.png'),
  GraphIcon: require('./graphIcon.png'),
  DotCircleIcon: require('./dotCircleIcon.png'),
  TrophyIcon: require('./trophyIcon.png'),
  BatBallOutlineIcon: require('./batBallOutlineIcon.png'),
  RightArrowIcon: require('./rightArrowIcon.png'),
  SettingIcon: require('./settingIcon.png'),
  StumpedOutIcon: require('./stumpedOutIcon.png'),
  CaughtOutIcon: require('./caughtOutIcon.png'),
  RunOutIcon: require('./runOutIcon.png'),
  LBWOutIcon: require('./LBWOutIcon.png'),
  WarningIcon: require('./warningIcon.png'),
};
